# Generated by Django 4.2.3 on 2023-07-10 16:51

import datetime

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('is_current_stack', models.BooleanField(default=True, verbose_name='Is Current Stack')),
            ],
        ),
        migrations.CreateModel(
            name='StackTimeRange',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'start_date',
                    models.DateField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                datetime.datetime(
                                    2023, 7, 10, 16, 51, 41, 45646, tzinfo=datetime.timezone.utc
                                )
                            )
                        ],
                        verbose_name='Start Date',
                    ),
                ),
                (
                    'end_date',
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                datetime.datetime(
                                    2023, 7, 10, 16, 51, 41, 45679, tzinfo=datetime.timezone.utc
                                )
                            )
                        ],
                        verbose_name='End Date',
                    ),
                ),
                (
                    'stack',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='time_range',
                        to='jobs.stack',
                        verbose_name='Stack',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name='Title',
                    ),
                ),
                (
                    'start_date',
                    models.DateField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                datetime.datetime(
                                    2023, 7, 10, 16, 51, 41, 46002, tzinfo=datetime.timezone.utc
                                )
                            )
                        ],
                        verbose_name='Start Date',
                    ),
                ),
                (
                    'end_date',
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                datetime.datetime(
                                    2023, 7, 10, 16, 51, 41, 46024, tzinfo=datetime.timezone.utc
                                )
                            )
                        ],
                        verbose_name='End Date',
                    ),
                ),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('url', models.URLField(verbose_name='Job URL')),
                ('logo', models.URLField(blank=True, max_length=500, null=True, verbose_name='Job Logo')),
                ('is_current_job', models.BooleanField(default=False, verbose_name='Is Current Job')),
                ('stack', models.ManyToManyField(to='jobs.stack', verbose_name='Stack')),
            ],
        ),
    ]
