# Generated by Django 5.0.2 on 2025-06-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_alter_timerange_end_date'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='time_range',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='job',
                to='core.timerange',
                verbose_name='Time Range',
            ),
        ),
        migrations.AlterField(
            model_name='stack',
            name='time_range',
            field=models.ManyToManyField(
                related_name='stack', to='core.timerange', verbose_name='Time Range'
            ),
        ),
    ]
