# Generated by Django 5.0.2 on 2025-07-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_time_range_alter_stack_time_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Logo URL'),
        ),
    ]
