# Generated by Django 5.0.2 on 2025-07-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_stack_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('jobs', models.ManyToManyField(related_name='service', to='jobs.job', verbose_name='Job')),
                ('stacks', models.ManyToManyField(related_name='service', to='jobs.stack', verbose_name='Stack')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
