# Generated by Django 5.0.2 on 2025-07-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0004_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='stacks',
            new_name='stack',
        ),
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Service URL'),
        ),
        migrations.AddField(
            model_name='service',
            name='url_logo',
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name='Service Logo URL'
            ),
        ),
    ]
