# Generated by Django 5.0.2 on 2025-07-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0005_rename_stacks_service_stack_service_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='is_current_stack',
            field=models.BooleanField(default=False, verbose_name='Is current stack'),
        ),
    ]
