# Generated by Django 5.0.2 on 2025-06-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timerange_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerange',
            name='label',
        ),
    ]
