# Generated by Django 5.0.2 on 2025-06-27 14:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_remove_timerange_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerange',
            name='end_date',
            field=models.DateField(
                default=datetime.date(2025, 6, 27),
                validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 6, 27))],
                verbose_name='End Date',
            ),
        ),
    ]
