"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1', cast=Csv())


# Application definition

UNFOLD_APPS = [
    'unfold',  # before django.contrib.admin
    'unfold.contrib.filters',  # optional, if special filters are needed
    'unfold.contrib.forms',  # optional, if special form elements are needed
    'unfold.contrib.inlines',  # optional, if special inlines are needed
    'unfold.contrib.import_export',  # optional, if django-import-export package is used
    'unfold.contrib.guardian',  # optional, if django-guardian package is used
    'unfold.contrib.simple_history',  # optional, if django-simple-history package is used
]

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

PROJECT_APPS = [
    'core',
    'jobs',
    'social',
]

DEBUG_APPS = ['debug_toolbar', 'django_extensions', 'livereload']
DEBUG_MIDDLEWARES = [
    'livereload.middleware.LiveReloadScript',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

INSTALLED_APPS = UNFOLD_APPS + DJANGO_APPS + PROJECT_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


if DEBUG:
    INSTALLED_APPS += DEBUG_APPS
    MIDDLEWARE += DEBUG_MIDDLEWARES

ROOT_URLCONF = 'backend.urls'


def debug_context(request):
    return {'debug': DEBUG}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'backend.settings.debug_context',
            ]
        },
    }
]


WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'productionfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = ['127.0.0.1']


UNFOLD = {
    'SITE_TITLE': 'Custom suffix in <title> tag',
    'SITE_HEADER': 'Appears in sidebar at the top',
    'SITE_SUBHEADER': 'Appears under SITE_HEADER',
    'SITE_DROPDOWN': [
        {
            'icon': 'diamond',
            'title': _('My site'),
            'link': 'https://example.com',
        },
        # ...
    ],
    # 'SITE_URL': '/',
    # # "SITE_ICON": lambda request: static("icon.svg"),  # both modes, optimise for 32px height
    # 'SITE_ICON': {
    #     'light': lambda request: static('icon-light.svg'),  # light mode
    #     'dark': lambda request: static('icon-dark.svg'),  # dark mode
    # },
    # # "SITE_LOGO": lambda request: static("logo.svg"),  # both modes, optimise for 32px height
    # 'SITE_LOGO': {
    #     'light': lambda request: static('logo-light.svg'),  # light mode
    #     'dark': lambda request: static('logo-dark.svg'),  # dark mode
    # },
    # 'SITE_SYMBOL': 'speed',  # symbol from icon set
    # 'SITE_FAVICONS': [
    #     {
    #         'rel': 'icon',
    #         'sizes': '32x32',
    #         'type': 'image/svg+xml',
    #         'href': lambda request: static('favicon.svg'),
    #     },
    # ],
    # 'SHOW_HISTORY': True,  # show/hide "History" button, default: True
    # 'SHOW_VIEW_ON_SITE': True,  # show/hide "View on site" button, default: True
    # 'SHOW_BACK_BUTTON': False,  # show/hide "Back" button on changeform in header, default: False
    # 'ENVIRONMENT': 'sample_app.environment_callback',  # environment name in header
    # 'ENVIRONMENT_TITLE_PREFIX': 'sample_app.environment_title_prefix_callback',  # environment name prefix in title tag
    # 'DASHBOARD_CALLBACK': 'sample_app.dashboard_callback',
    # 'THEME': 'dark',  # Force theme: "dark" or "light". Will disable theme switcher
    # 'LOGIN': {
    #     'image': lambda request: static('sample/login-bg.jpg'),
    #     'redirect_after': lambda request: reverse_lazy('admin:APP_MODEL_changelist'),
    # },
    # 'STYLES': [
    #     lambda request: static('css/style.css'),
    # ],
    # 'SCRIPTS': [
    #     lambda request: static('js/script.js'),
    # ],
    'BORDER_RADIUS': '6px',
    'COLORS': {
        'base': {
            '50': '249 250 251',
            '100': '243 244 246',
            '200': '229 231 235',
            '300': '209 213 219',
            '400': '156 163 175',
            '500': '107 114 128',
            '600': '75 85 99',
            '700': '55 65 81',
            '800': '31 41 55',
            '900': '17 24 39',
            '950': '3 7 18',
        },
        'primary': {
            '50': '250 245 255',
            '100': '243 232 255',
            '200': '233 213 255',
            '300': '216 180 254',
            '400': '192 132 252',
            '500': '168 85 247',
            '600': '147 51 234',
            '700': '126 34 206',
            '800': '107 33 168',
            '900': '88 28 135',
            '950': '59 7 100',
        },
        'font': {
            'subtle-light': 'var(--color-base-500)',  # text-base-500
            'subtle-dark': 'var(--color-base-400)',  # text-base-400
            'default-light': 'var(--color-base-600)',  # text-base-600
            'default-dark': 'var(--color-base-300)',  # text-base-300
            'important-light': 'var(--color-base-900)',  # text-base-900
            'important-dark': 'var(--color-base-100)',  # text-base-100
        },
    },
    'EXTENSIONS': {
        'modeltranslation': {
            'flags': {
                'en': '🇬🇧',
                'fr': '🇫🇷',
                'pt-br': '🇧🇷',
            },
        },
    },
    'SIDEBAR': {
        'show_search': False,  # Search in applications and models names
        'show_all_applications': False,  # Dropdown with all applications and models
        'navigation': [
            {
                'title': _('Navigation'),
                'separator': True,  # Top border
                'collapsible': True,  # Collapsible group of links
                'items': [
                    {
                        'title': _('Dashboard'),
                        'icon': 'dashboard',  # Supported icon set: https://fonts.google.com/icons
                        'link': reverse_lazy('admin:index'),
                        'badge': 'sample_app.badge_callback',
                        'permission': lambda request: request.user.is_superuser,
                    },
                    {
                        'title': _('Users'),
                        'icon': 'people',
                        'link': reverse_lazy('admin:auth_user_changelist'),
                    },
                    {
                        'title': _('Groups'),
                        'icon': 'group',
                        'link': reverse_lazy('admin:auth_group_changelist'),
                    },
                ],
            },
            {
                'title': _('Social'),
                'separator': True,  # Top border
                'collapsible': True,  # Collapsible group of links
                'items': [
                    {
                        'title': _('Addresses'),
                        'icon': 'map',
                        'link': reverse_lazy('admin:social_address_changelist'),
                    },
                    {
                        'title': _('Phone Numbers'),
                        'icon': 'phone',
                        'link': reverse_lazy('admin:social_phonenumber_changelist'),
                    },
                    {
                        'title': _('Social'),
                        'icon': 'person_add',
                        'link': reverse_lazy('admin:social_social_changelist'),
                    },
                    {
                        'title': _('Social Medias'),
                        'icon': 'share',
                        'link': reverse_lazy('admin:social_socialmedia_changelist'),
                    },
                ],
            },
            {
                'title': _('Jobs'),
                'separator': True,  # Top border
                'collapsible': True,  # Collapsible group of links
                'items': [
                    {
                        'title': _('Jobs'),
                        'icon': 'assignment_ind',
                        'link': reverse_lazy('admin:jobs_job_changelist'),
                    },
                    {
                        'title': _('Stacks'),
                        'icon': 'usb',
                        'link': reverse_lazy('admin:jobs_stack_changelist'),
                    },
                    {
                        'title': _('Time Ranges'),
                        'icon': 'calendar_month',
                        'link': reverse_lazy('admin:core_timerange_changelist'),
                    },
                ],
            },
        ],
    },
}
