"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config
from django.conf.urls.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
ENV = config('ENV', default='dev')

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1', cast=Csv())


# Application definition

UNFOLD_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'unfold.contrib.import_export',
    'unfold.contrib.guardian',
    'unfold.contrib.simple_history',
]

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'django_cleanup.apps.CleanupConfig',
]

PROJECT_APPS = [
    'core',
    'jobs',
    'social',
]

DEBUG_APPS = ['debug_toolbar', 'django_extensions', 'livereload']
DEBUG_MIDDLEWARES = [
    'livereload.middleware.LiveReloadScript',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

INSTALLED_APPS = UNFOLD_APPS + DJANGO_APPS + PROJECT_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


if DEBUG:
    INSTALLED_APPS += DEBUG_APPS
    MIDDLEWARE += DEBUG_MIDDLEWARES

ROOT_URLCONF = 'backend.urls'


def debug_context(request):
    return {'debug': DEBUG}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'backend.settings.debug_context',
            ]
        },
    }
]


WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DB = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3',
}

if ENV == 'prod':
    DB = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER'),
        'PASSWORD': config('POSTGRES_PASSWORD'),
        'HOST': config('POSTGRES_HOST'),
        'PORT': config('POSTGRES_PORT'),
    }

DATABASES = {
    'default': DB,
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'productionfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = ['127.0.0.1']


UNFOLD = {  # noqa: E501
    'SITE_TITLE': 'GomeSystems',
    'SITE_HEADER': 'GomeSystems',
    'SITE_SUBHEADER': 'Qualidade de ponta a ponta',
    'SITE_DROPDOWN': [
        {
            'icon': 'diamond',
            'title': _('Site'),
            'link': 'http://gomesystems.dev.br/' if ENV == 'prod' else 'http://localhost:8000/',
        },
    ],
    'STYLES': [
        lambda request: static('css/style.css'),
        lambda request: static('unfold/css/forms.css'),
    ],
    'BORDER_RADIUS': '6px',
    'COLORS': {
        'base': {
            '50': '249 250 251',
            '100': '243 244 246',
            '200': '229 231 235',
            '300': '209 213 219',
            '400': '156 163 175',
            '500': '107 114 128',
            '600': '75 85 99',
            '700': '55 65 81',
            '800': '31 41 55',
            '900': '17 24 39',
            '950': '3 7 18',
        },
        'primary': {
            '50': '250 245 255',
            '100': '243 232 255',
            '200': '233 213 255',
            '300': '216 180 254',
            '400': '192 132 252',
            '500': '168 85 247',
            '600': '147 51 234',
            '700': '126 34 206',
            '800': '107 33 168',
            '900': '88 28 135',
            '950': '59 7 100',
        },
        'font': {
            'subtle-light': 'var(--color-base-500)',  # text-base-500
            'subtle-dark': 'var(--color-base-400)',  # text-base-400
            'default-light': 'var(--color-base-600)',  # text-base-600
            'default-dark': 'var(--color-base-300)',  # text-base-300
            'important-light': 'var(--color-base-900)',  # text-base-900
            'important-dark': 'var(--color-base-100)',  # text-base-100
        },
    },
    'EXTENSIONS': {
        'modeltranslation': {
            'flags': {
                'en': '🇬🇧',
                'fr': '🇫🇷',
                'pt-br': '🇧🇷',
            },
        },
    },
    'SIDEBAR': {
        'show_search': False,  # Search in applications and models names
        'show_all_applications': False,  # Dropdown with all applications and models
        'navigation': [
            {
                'title': _('Navigation'),
                'separator': True,  # Top border
                'collapsible': True,  # Collapsible group of links
                'items': [
                    {
                        'title': _('Dashboard'),
                        'icon': 'dashboard',  # Supported icon set: https://fonts.google.com/icons
                        'link': reverse_lazy('admin:index'),
                        'badge': 'sample_app.badge_callback',
                        'permission': lambda request: request.user.is_superuser,
                    },
                    {
                        'title': _('Users'),
                        'icon': 'people',
                        'link': reverse_lazy('admin:auth_user_changelist'),
                    },
                    {
                        'title': _('Groups'),
                        'icon': 'group',
                        'link': reverse_lazy('admin:auth_group_changelist'),
                    },
                ],
            },
            {
                'title': _('Social'),
                'separator': True,  # Top border
                'collapsible': True,  # Collapsible group of links
                'items': [
                    {
                        'title': _('Addresses'),
                        'icon': 'map',
                        'link': reverse_lazy('admin:social_address_changelist'),
                    },
                    {
                        'title': _('Phone Numbers'),
                        'icon': 'phone',
                        'link': reverse_lazy('admin:social_phonenumber_changelist'),
                    },
                    {
                        'title': _('Social'),
                        'icon': 'person_add',
                        'link': reverse_lazy('admin:social_social_changelist'),
                    },
                    {
                        'title': _('Social Medias'),
                        'icon': 'share',
                        'link': reverse_lazy('admin:social_socialmedia_changelist'),
                    },
                ],
            },
            {
                'title': _('Jobs'),
                'separator': True,  # Top border
                'collapsible': True,  # Collapsible group of links
                'items': [
                    {
                        'title': _('Jobs'),
                        'icon': 'assignment_ind',
                        'link': reverse_lazy('admin:jobs_job_changelist'),
                    },
                    {
                        'title': _('Stacks'),
                        'icon': 'usb',
                        'link': reverse_lazy('admin:jobs_stack_changelist'),
                    },
                    {
                        'title': _('Time Ranges'),
                        'icon': 'calendar_month',
                        'link': reverse_lazy('admin:core_timerange_changelist'),
                    },
                    {
                        'title': _('Services'),
                        'icon': 'attach_money',
                        'link': reverse_lazy('admin:jobs_service_changelist'),
                    },
                ],
            },
        ],
    },
}
