# Generated by Django 5.0.2 on 2025-06-27 14:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(blank=True, max_length=12, null=True)),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborhood', models.CharField(max_length=50)),
                ('city', models.CharField(default='Salvador', max_length=50)),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('AC', 'Acre'),
                            ('AL', 'Alagoas'),
                            ('AP', 'Amapá'),
                            ('AM', 'Amazonas'),
                            ('BA', 'Bahia'),
                            ('CE', 'Ceará'),
                            ('DF', 'Distrito Federal'),
                            ('ES', 'Espírito Santo'),
                            ('GO', 'Goiás'),
                            ('MA', 'Maranhão'),
                            ('MT', 'Mato Grosso'),
                            ('MS', 'Mato Grosso do Sul'),
                            ('MG', 'Minas Gerais'),
                            ('PA', 'Pará'),
                            ('PB', 'Paraíba'),
                            ('PR', 'Paraná'),
                            ('PE', 'Pernambuco'),
                            ('PI', 'Piauí'),
                            ('RJ', 'Rio de Janeiro'),
                            ('RN', 'Rio Grande do Norte'),
                            ('RS', 'Rio Grande do Sul'),
                            ('RO', 'Rondônia'),
                            ('RR', 'Roraima'),
                            ('SC', 'Santa Catarina'),
                            ('SP', 'São Paulo'),
                            ('SE', 'Sergipe'),
                            ('TO', 'Tocantins'),
                        ],
                        default='BA',
                        max_length=2,
                    ),
                ),
                ('country', models.CharField(default='BRA', max_length=3)),
                ('zipcode', models.CharField(max_length=8, verbose_name='ZIP Code')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('prefix', models.CharField(default='71', max_length=2)),
                (
                    'number',
                    models.CharField(
                        max_length=12, validators=[django.core.validators.MinLengthValidator(8)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(default='GomeSystems', max_length=50)),
                ('author', models.CharField(default='Marcos Gomes', max_length=50)),
                ('about_us', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('founded_in', models.DateField(blank=True, null=True)),
                (
                    'address',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='social.address',
                        verbose_name='address',
                    ),
                ),
                (
                    'phone_number',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='social.phonenumber'
                    ),
                ),
                (
                    'social_media',
                    models.ManyToManyField(to='social.socialmedia', verbose_name='Social Media'),
                ),
            ],
        ),
    ]
