# Generated by Django 5.0.2 on 2025-07-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_social_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='social/thumbnail'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='url_logo',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
